# Generated by Django 4.2.20 on 2025-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../ember_hkln5k', upload_to='profile_images/'),
        ),
    ]
