# Generated by Django 4.2.20 on 2025-04-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletag',
            name='name',
            field=models.CharField(choices=[('writer', 'Writer'), ('artist', 'Artist'), ('photographer', 'Photographer')], max_length=50, unique=True),
        ),
    ]
