# Generated by Django 4.2.20 on 2025-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiletag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../ember_m0wtth', upload_to='profile_images/'),
        ),
    ]
