# Generated by Django 4.2.20 on 2025-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../ember_wv8ywv', upload_to='profile_images/'),
        ),
    ]
